# Travis CI (MIT License) configuration file for WordPress theme wd_s.
# @link https://travis-ci.org/

# For use with the WordPress theme wd_s.
# @link https://github.com/WebDevStudios/wd_s

sudo: false
language: php

matrix:
    fast_finish: true
    include:
        - php: '5.6'
        - php: '7.0'
        - php: '7.1'
        - php: '7.2'
    allow_failures:
        - php: '7.2'

install:
    - export COMPOSER_DIR=~/.composer/
    - export SNIFFS_DIR=/tmp/sniffs
    - nvm install node
    - nvm use node
    - npm install --global eslint eslint-config-wordpress sass-lint
    - composer global require webdevstudios/wds-coding-standards
    - git clone --branch master --depth=50 https://github.com/wimg/PHPCompatibility.git $SNIFFS_DIR/PHPCompatibility

before_script:
    - cd $TRAVIS_BUILD_DIR
    - $COMPOSER_DIR/vendor/bin/phpcs --config-set installed_paths $COMPOSER_DIR/vendor/wp-coding-standards/wpcs,$COMPOSER_DIR/vendor/webdevstudios/wds-coding-standards/WebDevStudios
    - $COMPOSER_DIR/vendor/bin/phpcs -i
    - phpenv rehash

script:
    - find -L ./ -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
    - $COMPOSER_DIR/vendor/bin/phpcs -p -s -v -n . --standard=WebDevStudios --extensions=php
    - eslint --config $COMPOSER_DIR/vendor/webdevstudios/wds-coding-standards/WebDevStudios/.eslintrc.js './assets/scripts/concat'
    - sass-lint --config $COMPOSER_DIR/vendor/webdevstudios/wds-coding-standards/WebDevStudios/.sass-lint.yml './assets/sass/**/*.scss' --verbose --no-exit

notifications:
  email: false
  slack:
    secure: lDFLE+EZrQu9phgxUFFekrH4nqdbeY/qDdOVYD4QRznHGdfNswn7HhVt7CAGjVHEiqkG9J6LzZCOxjy93TMoXgRr/hIBkqJI2oYDBwlEf0P3G0XiPEuWSQvm8Ao9N7nUoF2OlyeA44SRuFTrAbNKjlAw4Nwk08Ew3LjByREYJ6k=
